upload: ecg.hex
	sudo avrdude -v -c arduino -p atmega328p -D -P /dev/cuaU0 -U flash:w:ecg.hex:i

ecg.hex: ecg.out
	avr-objcopy -O ihex -R .eeprom ecg.out ecg.hex

ecg.out: ecg.c
	avr-gcc -DF_CPU=16000000UL -mmcu=atmega328p -o ecg.out ecg.c

.PHONY: upload
